name: Deploy ECS Fargate

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Do you want to destroy the resources?'
        required: true
        default: 'no'
        type: choice
        options:
          - yes
          - no

jobs:
  depoy-ecs-fargate:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      # Depoyu Klonla
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Terraform Kurulumu
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "latest"
          
        # AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: List files in tf-folder
        run: ls -l ./tf-folder
        
        #Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./tf-folder
      
      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./tf-folder

      # Terraform Apply (Otomatik Onay)
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve tfplan
      #   working-directory: ./tf-folder

      - name: Debug Destroy Input
        run: "Destroy input is: ${{ github.event.inputs.destroy }}"

      # Terraform Destroy (Otomatik Onay), sadece onay verilirse çalışacak. NOT: Bu aşama sadece deneme amacıyla yazıldı.
      - name: Terraform Destroy
        if: ${{ github.event.inputs.destroy == 'yes' }}
        run: terraform destroy -auto-approve
        working-directory: ./tf-folder