name: Deploy ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  depoy-ecs-fargate:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      # Depoyu Klonla
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Terraform Kurulumu
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5
          
        # AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: List files in tf-folder
        run: ls -l ./tf-folder
        
        #Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./tf-folder

      # Terraform Format Kontrolü
      - name: Terraform Fmt
        run: terraform fmt -check
        working-directory: ./tf-folder

      # Terraform Doğrulama
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./tf-folder

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./tf-folder

      # Terraform Apply (Otomatik Onay)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./tf-folder
      
       ## Terraform Apply (Otomatik Onay)
      - name: Terraform Destroy
        run: terraform destroy -auto-approve tfplan
        working-directory: ./tf-folder