name: Create Jira issue on new GitHub issue

on:
  issues:
    types: [opened]

jobs:
  create-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Build Jira payload
        id: payload
        run: |
          TITLE="${{ github.event.issue.title }}"
          BODY=$(printf "%s\n\nGitHub Issue: %s\nRepo: %s\nAuthor: %s" \
            "${{ github.event.issue.body }}" \
            "${{ github.event.issue.html_url }}" \
            "${{ github.repository }}" \
            "${{ github.actor }}")

          ITYPE="Bug"
          echo "::set-output name=data::$(jq -n \
            --arg project "${{ secrets.JIRA_PROJECT }}" \
            --arg summary "$TITLE" \
            --arg desc "$BODY" \
            --arg itype "$ITYPE" \
            '{fields:{project:{key:$project},summary:$summary,description:$desc,issuetype:{name:$itype}}}')"

      - name: Create Jira issue
        id: create
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL:     ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          RESP=$(curl -sS -w ":%{http_code}" -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data '${{ steps.payload.outputs.data }}' \
            "$JIRA_BASE_URL/rest/api/3/issue")
          BODY="${RESP%:*}"
          CODE="${RESP##*:}"
          echo "HTTP $CODE"
          echo "$BODY" > response.json
          if [ "$CODE" -ge 200 ] && [ "$CODE" -lt 300 ]; then
            KEY=$(jq -r '.key' response.json)
            echo "Created $KEY"
            echo "issue_key=$KEY" >> $GITHUB_OUTPUT
          else
            echo "Jira create failed:"
            cat response.json
            exit 1
          fi

      - name: Comment back on GitHub issue
        if: steps.create.outputs.issue_key != ''
        uses: actions/github-script@v7
        with:
          script: |
            const key = "${{ steps.create.outputs.issue_key }}";
            const url = `${{ secrets.JIRA_BASE_URL }}/browse/${key}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Created Jira issue **${key}** → ${url}`
            });
